routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('cart', [CartController::class, 'cartList'])->name('cart.list');
Route::post('cart', [CartController::class, 'addToCart'])->name('cart.store');
Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
Route::post('remove', [CartController::class, 'removeCart'])->name('cart.remove');
Route::post('clear', [CartController::class, 'clearAllCart'])->name('cart.clear');
Route::resource('review', ReviewController::class);
Route::resource('checkout', TransactionController::class);

resources/views/cart.blade.php
@extends('layouts.main')


@section('content')
<section class="section-space bg-white" id="#cart">
    <div class="container">
        <div class="col-sm-12 col-xl-6 xl-100 row d-flex justify-content-center">
            <div class="card col-12">
                <div class="card-header">
                    <h5>Cart</h5>
                    @if ($message = Session::get('success'))
                    <div class="p-4 mb-3 bg-green-400 rounded">
                        <p class="text-green-800">{{ $message }}</p>
                    </div>
                    @endif
                </div>
                <div class="card-block p-2 row">
                    <div class="col-sm-12 col-lg-12 col-xl-12">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">
                                            <span class="lg:hidden" title="Quantity">Qtd</span>
                                            <span class="hidden lg:inline">Quantity</span>
                                        </th>
                                        <th class="hidden text-right md:table-cell">Price</th>
                                        <th class="hidden text-right md:table-cell">Remove </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($cartItems as $item)
                                    <tr>
                                        <td class="hidden pb-4 md:table-cell">
                                            <a href="#">
                                                <img src="{{ $item->attributes->image }}" class="rounded"
                                                    alt="Thumbnail" style="max-width: 7rem">
                                            </a>
                                        </td>
                                        <td>
                                            <a href="#">
                                                <p class="mb-2 md:ml-4">{{ $item->name }}</p>

                                            </a>
                                        </td>
                                        <td class="justify-center mt-6 md:justify-end md:flex">
                                            <div class="h-10 w-28">
                                                <div class="relative flex flex-row w-full h-8">

                                                    <form action="{{ route('cart.update') }}" method="POST">
                                                        @csrf
                                                        <input type="hidden" name="id" value="{{ $item->id}}">
                                                        <div class="form-group row d-flex justify-content-center">
                                                            <input type="number" name="quantity"
                                                                value="{{ $item->quantity }}" class="form-control col-2"/>
                                                            <button type="submit" class="btn btn-info col-3 ml-2">update</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="hidden text-right md:table-cell">
                                            <span class="text-sm font-medium lg:text-base">
                                                Rp. {{ number_format($item->price) }}
                                            </span>
                                        </td>
                                        <td class="hidden text-right md:table-cell">
                                            <form action="{{ route('cart.remove') }}" method="POST">
                                                @csrf
                                                <input type="hidden" value="{{ $item->id }}" name="id">
                                                <button class="btn btn-info">x</button>
                                            </form>

                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <h4>Total: Rp. {{ number_format(Cart::getTotal()) }}</h4>
                    @if (count($cartItems) > 0)
                        <a href="#checkout" class="btn btn-info" data-toggle="collapse" data-target="#checkout">Checkout</a>
                    @endif
                    <form action="{{ route('cart.clear') }}" method="POST">
                        @csrf
                        <button class="btn btn-danger">Remove All Cart</button>
                    </form>
                </div>
            </div>
            @include('checkout')
        </div>
    </div>
</section>
@endsection

resources/views/checkout.blade.php
<div class="card col-6 collapse" id="checkout">
    <div class="card-header">
        <h5>Checkout</h5>
    </div>
    <div class="card-body">
        <form action="{{ route('checkout.store') }}" method="POST" class="w-100 row">
            @csrf
            <input type="text" name="user_id" id="user_id" value="{{Auth::id()}}" hidden>
            <input type="text" name="subtotal" id="subtotal" value="{{Cart::getTotal()}}" hidden>
            <div class="form-group col-12">
                <label for="nama">Atas Nama</label>
                <input type="text" class="form-control" name="nama" id="nama"
                    value="{{Auth::user()->name}}">
            </div>
            <div class="form-group col-12">
                <label for="no_meja">No. Meja</label>
                <input type="number" class="form-control" name="no_meja" id="no_meja">
            </div>
            <div class="form-group col-12">
                <label for="is_cash">Metode Pembayaran</label>
                <select name="is_cash" id="is_cash" class="form-control">
                    <option value="1">Cash</option>
                    <option value="0">Debit dan metode pembayaran lain</option>
                </select>
            </div>
            <div class="form-group col-12">
                <label for="nominal">Nominal</label>
                <input type="number" class="form-control" name="nominal" id="nominal">
            </div>
        </div>
        <div class="card-footer d-flex justify-content-end">
            <button type="submit" class="btn btn-danger">Checkout</button>
        </div>
    </form>
</div>

resources/views/home.blade.php
@extends('layouts.main')
@section('content')
<!--admin option section start-->
<section class="section-space bg-white" id="menus">
    <div class="container">
        <div class="col-sm-12 col-xl-6 xl-100">
            <div class="card">
                <div class="card-header">
                    <h5>Our Menus</h5>
                    <span><b>cast</b>, <span class="txt-success">choose</span> and <span
                            class="txt-danger">chill</span></span>
                </div>
                <div class="card-body">
                    <ul class="nav nav-tabs nav-material nav-primary" id="info-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="info-home-tab" data-toggle="tab" href="#info-home" role="tab"
                                aria-controls="info-home" aria-selected="true">
                                <i class="fa fa-cutlery"></i>Food</a>
                            <div class="material-border"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-info-tab" data-toggle="tab" href="#info-profile" role="tab"
                                aria-controls="info-profile" aria-selected="false"><i class="fa fa-glass"></i>Drink</a>
                            <div class="material-border"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="contact-info-tab" data-toggle="tab" href="#info-contact" role="tab"
                                aria-controls="info-contact" aria-selected="false">
                                <i class="fa fa-spoon"></i>Siders</a>
                            <div class="material-border"></div>
                        </li>
                    </ul>
                    <div class="tab-content" id="info-tabContent">
                        <div class="tab-pane fade show active" id="info-home" role="tabpanel"
                            aria-labelledby="info-home-tab">
                            <div class="row">
                                @foreach ($makanan as $key => $food)
                                <form id="formAdd{{$food->id}}" action="{{ route('cart.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" value="{{ $food->id }}" name="id">
                                    <input type="hidden" value="{{ $food->nama }}" name="name">
                                    <input type="hidden" value="{{ $food->harga }}" name="price">
                                    <input type="hidden" value="{{ $food->foto }}"  name="image">
                                    <input type="hidden" value="1" name="quantity">
                                </form>
                                <div class="col-xl-3 col-sm-6">
                                    <div class="card" style="height: 400px">
                                        <div class="product-box">
                                            <div class="product-img">
                                                <img src="{{$food->foto}}"
                                                    class="img-fluid" alt="" onerror="this.onerror=null; this.src='{{asset('assets/images/ecommerce/product/01.jpg')}}'" style="width: 200px; height: 250px;"/>
                                                <div class="product-hover">
                                                    <ul>
                                                        <li><a class="addToCart" data-id="{{$food->id}}"><i class="icon-shopping-cart"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="product-details">
                                                <h6>{{$food->nama}}</h6>
                                                <p>{{$food->jenis}}</p>
                                                <div class="product-price">
                                                    Rp. {{number_format($food->harga)}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="tab-pane fade" id="info-profile" role="tabpanel" aria-labelledby="profile-info-tab">
                            <div class="row">
                                @foreach ($minuman as $drink)
                                <form id="formAdd{{$drink->id}}" action="{{ route('cart.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" value="{{ $drink->id }}" name="id">
                                    <input type="hidden" value="{{ $drink->nama }}" name="name">
                                    <input type="hidden" value="{{ $drink->harga }}" name="price">
                                    <input type="hidden" value="{{ $drink->foto }}"  name="image">
                                    <input type="hidden" value="1" name="quantity">
                                </form>
                                <div class="col-xl-3 col-sm-6">
                                    <div class="card" style="height: 400px">
                                        <div class="product-box">
                                            <div class="product-img">
                                                <img src="{{$drink->foto}}"
                                                    class="img-fluid" alt="" onerror="this.onerror=null; this.src='{{asset('assets/images/ecommerce/product/01.jpg')}}'" style="width: 200px; height: 250px;"/>
                                                <div class="product-hover">
                                                    <ul>
                                                        <li><a class="addToCart" data-id="{{$drink->id}}"><i class="icon-shopping-cart"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="product-details">
                                                <h6>{{$drink->nama}}</h6>
                                                <p>{{$drink->jenis}}</p>
                                                <div class="product-price">
                                                    Rp. {{number_format($drink->harga)}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="tab-pane fade" id="info-contact" role="tabpanel" aria-labelledby="contact-info-tab">
                            <div class="row">
                                @foreach ($snack as $sider)
                                <form id="formAdd{{$sider->id}}" action="{{ route('cart.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" value="{{ $sider->id }}" name="id">
                                    <input type="hidden" value="{{ $sider->nama }}" name="name">
                                    <input type="hidden" value="{{ $sider->harga }}" name="price">
                                    <input type="hidden" value="{{ $sider->foto }}"  name="image">
                                    <input type="hidden" value="1" name="quantity">
                                </form>
                                <div class="col-xl-3 col-sm-6">
                                    <div class="card" style="height: 400px">
                                        <div class="product-box">
                                            <div class="product-img">
                                                <img src="{{$sider->foto}}"
                                                    class="img-fluid" alt="" onerror="this.onerror=null; this.src='{{asset('assets/images/ecommerce/product/01.jpg')}}'" style="width: 200px; height: 250px;"/>
                                                <div class="product-hover">
                                                    <ul>
                                                        <li><a class="addToCart" data-id="{{$sider->id}}"><i class="icon-shopping-cart"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="product-details">
                                                <h6>{{$sider->nama}}</h6>
                                                <p>{{$sider->jenis}}</p>
                                                <div class="product-price">
                                                    Rp. {{number_format($sider->harga)}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--admin option section ends-->
@endsection
@section('js')
    <script>
        $(document).on('click', '.addToCart', function(){
            let id = $(this).data('id');
            console.log(id);
            $(`#formAdd${id}`).submit();
        });
    </script>
@endsection

resources/views/invoice.blade.php
@extends('layouts.main')
@section('content')
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="invoice">
                        <div>
                            <div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="media">
                                            <div class="media-left">
                                                <img src="{{asset('assets/images/logo-alfath.png')}}" class="media-object img-60" alt="">
                                            </div>
                                            <div class="media-body m-l-20">
                                                <h4 class="media-heading">Alfath Cafe</h4>
                                                <p>hello@alfathcafe.com<br>
                                                    <span class="digits">(62) 812-6296-4751</span>
                                                </p>
                                            </div>
                                        </div>
                                        <!--End Info-->
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="text-md-right">
                                            <h3>Invoice #<span class="digits counter">{{$transaction->id}}</span></h3>
                                            <p>Issued: {{$transaction->created_at}}</span><br>
                                                Payment Due: {{$transaction->created_at}}</span>
                                            </p>
                                        </div><!--End Title-->
                                    </div>
                                </div>
                            </div>
                            <hr/>
                            <!--End InvoiceTop-->
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="media">
                                        <div class="media-left">
                                            <img src="https://img.icons8.com/external-inipagistudio-mixed-inipagistudio/64/000000/external-person-self-improvement-inipagistudio-mixed-inipagistudio.png"/>
                                        </div>
                                        <div class="media-body m-l-20">
                                            <h4 class="media-heading">{{$transaction->user->name}}</h4>
                                            <p>{{$transaction->user->email}}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div id="project" class="text-md-right">
                                        <h6>Terimakasih telah memesan</h6>
                                        <p>Mohon ditunggu pesanan akan segera diproses</p>
                                    </div>
                                </div>
                            </div>
                            <!--End Invoice Mid-->

                            <div class="mt-2">
                                <div id="table" class="table-responsive invoice-table">
                                    <table class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Name</th>
                                                <th scope="col">
                                                    <span class="lg:hidden" title="Quantity">Qtd</span>
                                                    <span class="hidden lg:inline">Quantity</span>
                                                </th>
                                                <th class="hidden text-right md:table-cell">Price</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($transaction->details as $item)
                                            <tr>
                                                <td class="hidden pb-4 md:table-cell">
                                                    <a href="#">
                                                        <img src="{{ $item->product->foto }}" class="rounded"
                                                            alt="Thumbnail" style="max-width: 7rem">
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="#">
                                                        <p class="mb-2 md:ml-4">{{ $item->product->nama }}</p>

                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="#">
                                                        <p class="mb-2 md:ml-4">{{ $item->qty }}</p>

                                                    </a>
                                                </td>
                                                <td class="hidden text-right md:table-cell">
                                                    <span class="text-sm font-medium lg:text-base">
                                                        Rp. {{ number_format($item->product->harga) }}
                                                    </span>
                                                </td>
                                            </tr>
                                            @endforeach
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td>Total</td>
                                                <td>Rp. {{number_format($transaction->subtotal)}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div><!--End Table-->
                            </div>
                            <!--End InvoiceBot-->

                        </div>
                        <!--End Invoice-->

                    </div>
                    <!-- End Invoice Holder-->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection