routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('cart', [CartController::class, 'cartList'])->name('cart.list');
Route::post('cart', [CartController::class, 'addToCart'])->name('cart.store');
Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
Route::post('remove', [CartController::class, 'removeCart'])->name('cart.remove');
Route::post('clear', [CartController::class, 'clearAllCart'])->name('cart.clear');
Route::resource('review', ReviewController::class);
Route::resource('checkout', TransactionController::class);

resources/views/partials/footer.blade.php
<!--footer start-->
<section class="section-space footer-bg" id="rateus">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>if you like our products Please Rate Us</h2>
                <div class="star-rate">
                    <i class="fa fa-star font-danger"></i>
                    <i class="fa fa-star font-danger"></i>
                    <i class="fa fa-star font-danger"></i>
                    <i class="fa fa-star font-danger"></i>
                    <i class="fa fa-star font-danger"></i>
                </div>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">
                    Rate Us
                </button>
                <style>
                    div.stars {
                        width: 270px;
                        display: inline-block
                    }

                    input.star {
                        display: none
                    }

                    label.star {
                        float: right;
                        padding: 10px;
                        font-size: 36px;
                        color: #4A148C;
                        transition: all .2s
                    }

                    input.star:checked~label.star:before {
                        content: '\f005';
                        color: #FD4;
                        transition: all .25s
                    }

                    input.star-5:checked~label.star:before {
                        color: #FE7;
                        text-shadow: 0 0 20px #952
                    }

                    input.star-1:checked~label.star:before {
                        color: #F62
                    }

                    label.star:hover {
                        transform: rotate(-15deg) scale(1.3)
                    }

                    label.star:before {
                        content: '\f006';
                        font-family: FontAwesome
                    }
                </style>
                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalCenter" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Review Us</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <!-- star rating -->
                                <div class="rating-wrapper">
                                    <div class="container d-flex justify-content-center">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="stars">
                                                    <form action="{{ route('review.store') }}" method="POST">
                                                        @csrf
                                                        <input class="star star-5" id="star-5" value="5" type="radio" name="star" />
                                                        <label class="star star-5" for="star-5"></label>
                                                        <input class="star star-4" id="star-4" value="4" type="radio" name="star" />
                                                        <label class="star star-4" for="star-4"></label>
                                                        <input class="star star-3" id="star-3" value="3" type="radio" name="star" />
                                                        <label class="star star-3" for="star-3"></label>
                                                        <input class="star star-2" id="star-2" value="2" type="radio" name="star" />
                                                        <label class="star star-2" for="star-2"></label>
                                                        <input class="star star-1" id="star-1" value="1" type="radio" name="star" />
                                                        <label class="star star-1" for="star-1"></label>
                                                        <input type="text" value="{{Auth::id()}}" name="user_id" hidden>
                                                        <div class="form-group">
                                                            <label for="comment">Komentar : </label>
                                                            <textarea name="comment" id="comment" class="form-control" rows="10"></textarea>
                                                        </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--footer ends-->

resources/views/partials/header.blade.php
<div class="landing-home">
    <div class="landing-header">
        <div class="container-fluid" style="padding: 0; margin:0;">
            <nav class="navbar navbar-expand-lg fixed-top bg-white">
                <a class="navbar-brand" href="#"><img src="{{asset('assets/images/logo-alfath.png')}}" class="img-fluid" alt=""/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon">
                    <i class="fa fa-bars"></i>
                </span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('cart.list')}}" class="btn bg-transparent"><i class="fa fa-shopping-bag"></i> Cart <span class="badge badge-dark">{{ Cart::getTotalQuantity()}}</span></a>
                        </li>
                        <li class="nav-item onhover-dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>
                            <ul class="profile-dropdown onhover-show-div p-20">
                                <li>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="landing-body">
        <div class="container-fluid" style="margin-top: 200px;">
            <div class="row">
                <div class="col-lg-4 offset-lg-2 dashboard-image-pt-xs offset-md-1 col-md-5 offset-sm-0">
                    <div class="landing-left bg-grey">
                        <div>
                            <h1><span class="txt-danger">Alfath</span> Cafe and Working Space</h1>
                            <h5> <span class="digits txt-primary f-w-700 f-26">30+ </span> menus ,<span class="digits txt-info f-w-700 f-26"> 20+</span> drink , <span class="digits txt-danger f-w-700 f-26">  10+ </span> beverages</h5>
                            <p class="pr-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Non nulla architecto molestiae accusantium libero qui, voluptas illum tempore fugit rem, laboriosam impedit eaque. Magni, eveniet eligendi optio ducimus incidunt amet?</p>
                            <div class="button-bottom">
                                <a href="{{ route('home')}}/#menus" class="btn btn-primary mr-2">Menus</a>
                                <a href="#rateus" class="btn btn-outline-primary-2x">Review Our Service</a>
                                <br>
                                <a href="{{ route('cart.list')}}/#cart" class="btn btn-secondary mt-2"><i class="fa fa-shopping-bag"></i> Cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pr-0 col-md-6">
                    <img src="#" class="img-fluid" alt=""/>
                </div>
            </div>
        </div>
    </div>
</div>